# Uncoast Unconference - Midwestern Conversations
c("Yaa Suure",
  "It's so warm out today",
  "Oofta",
  "Not too bad",
  "Hotdish/Casserole",
  "Have you been to the state fair?",
  "I've got a cousin who lives there",
  "Isn't that where Field of Dream was filmed?",
  "Ole and Lena",
  "Zombie Burger is sooo good",
  "Amana Colonies",
  "Hawkeyes",
  "Cyclones",
  "Huskers",
  "Gophers",
  "Don'tcha Know",
  "flyover country",
  "I remember the Metrodome",
  "Corn Fields for X hours",
  "We got X inches of snow",
  "Road construction",
  "Winter duration",
  "Lefsa",
  "Boundary Waters"
)
